package(default_visibility = ["//visibility:public"])

py_library(
    name = "kitti",
    srcs = ["kitti.py"],
    deps = [
        "//mvg:basic",
        "//mvg:camera",
        "//mvg:image_processing",
    ],
)
