package(default_visibility = ["//visibility:public"])

py_library(
    name = "basic",
    srcs = ["basic.py"],
)

py_library(
    name = "calibration",
    srcs = ["calibration.py"],
)

py_library(
    name = "camera",
    srcs = ["camera.py"],
    deps = ["//mvg:image_processing"],
)

py_library(
    name = "features",
    srcs = ["features.py"],
)

py_library(
    name = "homography",
    srcs = ["homography.py"],
)

py_library(
    name = "stereo",
    srcs = ["stereo.py"],
)

py_library(
    name = "image_processing",
    srcs = ["image_processing.py"],
)
